from aiogram.filters.callback_data import CallbackData

class FeedBackCallback(CallbackData, prefix="feedback"):
    ...

class CloseFeedBackCallback(CallbackData, prefix="close_feedback"):
    ...

class RefreshCallback(CallbackData, prefix="refresh"):
    ...

class FeedBackSendedCallback(CallbackData, prefix="feedback_sent"):
    ...